---
- hosts: all
  vars:
    packages:
      - git-all
  tasks:
  - name: Install dependencies
    yum:
      name: "{{packages}}"
      state: present
    become: yes

  - name: Clone git repo
    git :
      repo: https://github.com/aakashkapur/ansible-repo.git
      dest: /home/aakash/hello
