---
- hosts: all
  vars:
    packages:
      - git
  tasks:
  - name: Gather rpm package facts
    package_facts:
      manager: auto

  - name: if git is installed
    debug:
      msg: "{{ansible_facts.packages['git']}}"
    when: "'git' in ansible_facts.packages"

  - name: if git is not installed
    yum:
      name: "{{packages}}"
      state: present
    become: yes
    when: "'git' not in ansible_facts.packages"

  - name: Clone git repo
    git :
      repo: https://github.com/aakashkapur/ansible-repo.git
      dest: /home/aakash/hello
