---
- hosts: all
  become: yes

  vars:
    db_package: mariadb-server
    db_service: mariadb
    db_users:
      - db_admin
      - db_user
    configure_database_path: /etc/my.cnf

  tasks:
  - name: Create mariaDb users
    user:
      name: "{{ item }}"
    loop: "{{ db_users }}"
    when : inventory_hostname in groups['db']

  - name: Install database server
    yum:
      name: "{{ db_package }}"
    when: db_package is defined and inventory_hostname in groups['db']

  - name: Configure database software
    import_tasks: configure_database.yml
    vars:
      extra_packages:
        - mariadb-bench
        - mariadb-libs
        - mariadb-test
    when: configure_database_path is defined and inventory_hostname in groups['db']
