---
- name: This installs Nginx on host machines
  vars:
    packages:
      - nginx
      - nginx-extras


  tasks:
  - name: Install Nginx
    yum: 
      name: "{{packages}}"
      state: present

  - name: Configure Nginx
    template: "src=nginx.conf.template  dest=/etc/nginx/nginx.conf"
    notify: restart nginx

  - name: Configure Virtual host
    template: "src=virtualhost.template dest=/etc/nginx/sites-available/default"
    notify: restart nginx    
